name: Example Workflow with Warning and File Upload

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add your logic to generate or upload failures_summary.json
      - name: Upload failures_summary.json (example step)
        run: |
          echo '{"failure_count": 3, "details": ["Test1 failed", "Test2 failed", "Test3 failed"]}' > failures_summary.json
          
      - name: Display the content of failures_summary.json in a warning
        run: |
          # Read the contents of the JSON file
          JSON_CONTENT=$(cat failures_summary.json)
          echo "### Warnings from Failure Summary" >> $GITHUB_STEP_SUMMARY
          echo "$JSON_CONTENT" >> $GITHUB_STEP_SUMMARY
          # Display a warning in the logs with the file content
          echo "::warning::$(cat failures_summary.json)"

      - name: Add warning to summary
        run: |
          echo "::set-output name=warning::$(cat failures_summary.json)"
