name: Example Workflow with Warning and File Upload

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add your logic to generate or upload failures_summary.json
      - name: Upload failures_summary.json (example step)
        run: |
          echo '{"failure_count": 3, "details": ["Test1 failed", "Test2 failed", "Test3 failed"]}' > failures_summary.json
          
      - name: Display the content of failures_summary.json in a warning
        run: |
          # Read the contents of the JSON file
          JSON_CONTENT=$(cat failures_summary.json)
          
          # Output to the summary
          echo "### Warnings from Failure Summary" >> $GITHUB_STEP_SUMMARY
          echo "$JSON_CONTENT" >> $GITHUB_STEP_SUMMARY
          
          # Display a warning in the logs with the file content
          echo "::warning::$(cat failures_summary.json)"
          
          # Save output to an environment file (this is the new way to set output)
          echo "WARNING_OUTPUT=$JSON_CONTENT" >> $GITHUB_ENV

      - name: Use warning output in the next step
        run: |
          echo "This is the warning content from the previous step: $WARNING_OUTPUT"

          name: Example Workflow with Warning Annotations

      - name: Read failures_summary.json and add annotations
        run: |
          # Read the contents of the JSON file
          JSON_CONTENT=$(cat failures_summary.json)
          
          # Add the contents as a warning annotation
          echo "::warning file=failures_summary.json::Failures detected: $JSON_CONTENT"
          
          # If you want to add multiple warnings (e.g., for each failure):
          echo "::warning file=failures_summary.json::Failure count: 3"
          echo "::warning file=failures_summary.json::Test1 failed"
          echo "::warning file=failures_summary.json::Test2 failed"
          echo "::warning file=failures_summary.json::Test3 failed"
          
          # Optionally save the warning message to the environment if needed for subsequent steps
          echo "WARNING_OUTPUT=$JSON_CONTENT" >> $GITHUB_ENV

      - name: Use warning output in the next step
        run: |
          echo "This is the warning content from the previous step: $WARNING_OUTPUT"
