name: Example Workflow with Warning and File Upload

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install jq
        run: sudo apt-get install jq

      - name: Read failures_summary.json and add annotations
        run: |
          python scripts/tmp/test.py
          
          echo "cat failures_summary.json"
          cat failures_summary.json
          
          JSON_CONTENT=$(cat failures_summary.json)
          ESCAPED_JSON_CONTENT=$(echo "$JSON_CONTENT" | jq -c '.')

          echo "::warning file=failures_summary.json::Failures detected: $ESCAPED_JSON_CONTENT"

          # rm failures_summary.json
          # rm $GITHUB_STEP_SUMMARY
