name: Check Nightly Build Status
on:
  workflow_call:
    inputs:
      nightly-build:
        required: true
        type: string
      platform: 
        required: false
        type: string
      runs-on:
        required: true
        type: string
    outputs:
      run_url:
        description: "Stores run URL."
        value: ${{ jobs.check-build.outputs.run_url }}
      run_conclusion: 
        description: "If nightly-build's conclusion."
        value: ${{ jobs.check-build.outputs.run_conclusion }}
      run_id:
        description: "Stores run id."
        value: ${{ jobs.check-build.outputs.run_id }}
      
env:
  GH_TOKEN: ${{ github.token }}
  GH_REPO: duckdb/duckdb
jobs:
  check-build:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout the repo with the script
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install DuckDB for Python
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install duckdb --pre --upgrade
          pip install duckdb pandas tabulate
      
      - name: Create ${{ inputs.nightly-build }} run status report
        shell: bash
        run: |
          failures_count=$(python scripts/create_build_report.py ${{ inputs.nightly-build }})

          if [ failures_count == 0 ]; then
            echo 
          fi

      - name: Upload Run Status file
        uses: actions/upload-artifact@v4
        with:
          name: build_report_${{ inputs.nightly-build }}
          path: build_report_${{ inputs.nightly-build }}.md