name: Publish Report to GitHub Pages

on:
  workflow_run:
    workflows: ["Check Nightly Build Status"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Download report artifact
        uses: actions/download-artifact@v4
        with:
          name: REPORT
          path: REPORT.md

      - name: Move report to docs folder
        run: |
          mkdir -p docs
          mv reports/REPORT.md docs/latest_report.md
          git add docs/latest_report.md

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update daily report $(date +'%Y-%m-%d')"
          branch: gh-pages
          file_pattern: reports/REPORT.md
