name: Publish Report to GitHub Pages

on:
  workflow_run:
    workflows: ["Check Nightly Build Status"]
    types:
      - completed
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: write
    pages: write
    id-token: write
    
    # Allow one concurrent deployment
concurrency:
    group: "pages"
    cancel-in-progress: true
env:
    GH_TOKEN: ${{ github.token }}
jobs:
  deploy:
    environment:
        name: github-pages
        # url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Download report artifact
        shell: bash
        run: |
            gh run list -w "Check Nightly Build Status" -L 1 --json databaseId --jq '.[] | .databaseId' > run_id
            gh run download $(cat run_id) -n REPORT
            ls
  
      - id: curr-date
        run: echo "date=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT

      - name: Move report to reports folder
        run: |
            mkdir -p docs
            mkdir -p reports
            cp ${{ steps.curr-date.outputs.date }}_REPORT_FILE.md reports
            ls -l reports/
            git add reports/${{ steps.curr-date.outputs.date }}_REPORT_FILE.md

      - name: Convert Markdown to HTML
        run: |
            sudo apt-get install -y pandoc  # Устанавливаем pandoc
            pandoc -o docs/index.html reports/${{ steps.curr-date.outputs.date }}_REPORT_FILE.md
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: "Update daily report $(date +'%Y-%m-%d')"
            branch: gh-pages
            file_pattern: docs/index.html
    #   - name: Set up Pages
    #     uses: actions/configure-pages@v5

    #   - name: Upload Pages Artifact
    #     uses: actions/upload-pages-artifact@v3
    #     with:
    #         path: docs/

    #   - name: Deploy to GitHub Pages
    #     id: deployment
    #     uses: actions/deploy-pages@v4

    #   - name: Commit and push changes
    #     uses: stefanzweifel/git-auto-commit-action@v5
    #     with:
    #         commit_message: "Update daily report $(date +'%Y-%m-%d')"
    #         branch: gh-pages
    #         file_pattern: docs/${{ steps.curr-date.outputs.date }}_REPORT_FILE.md