name: Publish Report to GitHub Pages

on:
  workflow_run:
    workflows: ["Check Nightly Build Status"]
    types:
      - completed
  workflow_dispatch:
env:
    GH_TOKEN: ${{ github.token }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Download report artifact
        shell: bash
        run: |
            gh run list -w "Check Nightly Build Status" -L 1 --json databaseId --jq '.[] | .databaseId' > run_id
            gh run download $(cat run_id) -n REPORT
            ls

      - name: Move report to docs folder
        run: |
            mkdir -p docs
            mkdir -p _posts
            cp *REPORT_FILE.md _posts/
            mv *REPORT_FILE.md docs/
            git add _posts/*REPORT_FILE.md
            
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
            ruby-version: '2.7'

      - name: Install Dependencies
        run: |
            gem install jekyll bundler
            bundle install
    
      - name: Build Jekyll Site
        run: bundle exec jekyll build

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update daily report $(date +'%Y-%m-%d')"
          branch: gh-pages
          file_pattern: _posts/*REPORT_FILE.md
