name: Windows
on:
  workflow_dispatch
jobs:
  upterm:
    name: Run upterm
    runs-on: windows-2019
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.10'
      - name: Install DuckDB for Python
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install duckdb --pre --upgrade
          pip install duckdb pandas tabulate requests
              
      - name: Checkout the repo with the script
        uses: actions/checkout@v4
      
      - name: Setup venv and Install requirements
        shell: bash
        run: | 
          mkdir -p .venv
          python -m venv .venv
          if [[ '${{ matrix.inputs.nightly_build }}' == 'Windows' || '${{ matrix.inputs.runs_on }}' == 'windows-2019' ]]; then
            # Install pyenv-win on Windows
            git clone https://github.com/pyenv-win/pyenv-win.git $HOME/.pyenv
            .venv/Scripts/activate
          else
            curl https://pyenv.run | bash
            source .venv/bin/activate
          fi
          pip install --upgrade pip
          pip install -r requirements.txt
      - uses: owenthereal/action-upterm@v1